### ISSUE TITLE
Question about email server

### ISSUE THREAD

**Issue by jeffjzx** [pallets-eco/flask-mail#105]
Hi, i'm new to email stuff. In my web app under development, i'm going to use email as an important part, such as when user signup and need activate or change some information that is sensitive. In either case, i need to send user some random generated tokens automatically. However, in ordinary email server such as gmail, there is limit of emails that i can send to the user.

How most company deal with this common practice? Thank you.

**Comment by davidism** [comment]
This is outside the scope of this project's issue tracker.
