### ISSUE TITLE
Does it continue to development?

### ISSUE THREAD

**Issue by TonyPythoneer** [pallets-eco/flask-mail#122]
I find this project almost hasn't recently commit and the newest commit is on 5 Nov 2014.

What's going on?

**Comment by Frozenball** [comment]
It seems like this project is abandoned (It's a lot of work to maintain open source projects!). Surprisingly, I didn't found any alternatives for this.

**Comment by Avamander** [comment]
@mattupstate Any chance of appointing new maintainers? I mean I'd gladly get some of the things sorted here, I'm also one of the maintainers of RF24(*) so I'd have the experience to help.

**Comment by bersace** [comment]
There is a new project at https://github.com/waynerv/flask-mailman . hope it'll get better governance.

**Comment by wlach** [comment]
This project is now a part of pallets-eco, and is being actively developed.

**Comment by davidism** [comment]
Flask-Mail is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on [the Pallets Discord server](https://discord.gg/pallets).
