### ISSUE TITLE
Sending mail via Gmail is very slow (~minute)

### ISSUE THREAD

**Issue by dkerkow** [pallets-eco/flask-mail#127]
Sending mail from my dev machine works fine using Gmail as STMP. But when I run the same config (and all possible variations of it) on the production machine, I get nginx timeouts, because sending is so slow. Is it possible that Gmail throttles down mails sent from known server IPs? What can I do to debug the process?

**Comment by davidism** [comment]
This isn't something Flask-Mail can control or debug for you.
