### ISSUE TITLE
Changelog missing from source tarball

### ISSUE THREAD

**Issue by Natureshadow** [pallets-eco/flask-mail#146]
The CHANGES file is missing from the source tarball, but is referenced from the sphinx docs.

Please add CHANGES to the manifest.

**Comment by davidism** [comment]
The sdist is an intermediate build that describes how to build and install a wheel locally when a wheel is not available. Adding docs, tests, etc. is not actually required as part of that build process. You can find the docs, tests, etc. as part of this repo, the canonical source.

**Comment by Natureshadow** [comment]
The canonical source is a released source tarball. It is supposed to contain everything to build and test the software.

**Comment by davidism** [comment]
There is no "released source tarball" on PyPI. There is an sdist, which is a specific build artifact that is produced _from_ the source as an intermediate step towards a wheel artifact. Docs and tests are not required to build an sdist into a wheel. You can download a source tarball from the source (the repo), for example https://github.com/pallets-eco/flask-mail/archive/refs/tags/0.9.1.tar.gz.
