### ISSUE TITLE
Email rejected by server when sender name is short

### ISSUE THREAD

**Issue by eanon** [pallets-eco/flask-mail#167]
Hello, I can't explain this, but in the code below, **when sender is less than 5 characters, the mail is rejected by the remote SMTP server with an error message like this one**:

> SMTP error from remote server for TEXT command, host: smtpz4.laposte.net (194.117.213.1) reason: 560 5.7.1 Service refuse. Service refused. LPN007_510 

Looking at detail, I see that the FROM field starts with "=?utf-8?q?", for example:

> From: =?utf-8?q?club?= <admin@club.xx>

**If I add one single character to the sender name (eg. "cluby" instead of "club"), the error disappears.**

Here is the code for sending:

```
def send_async_email(the_app, msg):
    with the_app.app_context():
        mail.send(msg)

def send_email(subject, sender, recipients, text_body, html_body):
    msg = Message(subject, sender=sender, recipients=recipients)
    msg.body = text_body
    msg.html = html_body
    Thread(target=send_async_email, args=(app, msg)).start()
```

with passed sender as:

```
sender = '%s <%s>' % (app.config['APP_NAME'], app.config['MAIL_USERNAME'])
```

For infos, I'm using Flask-Mail 0.9.1 with Flask 1.0.2 in Python 3.7.2 32-bit under Windows 7 64-bit.

**Comment by davidism** [comment]
I can't reproduce this issue.
