### ISSUE TITLE
Question: Is this still maintained?

### ISSUE THREAD

**Issue by tiny-dancer** [pallets-eco/flask-mail#168]

**Comment by eanon** [comment]
I'm wondering too... No reply the issue#167 I posted 24 days ago.

**Comment by noirbizarre** [comment]
I think this is the case: no commit or merged pull-request since 2014 :/

Might be the time to find a working fork or to start one

**Comment by bersace** [comment]
@noirbizarre see https://github.com/waynerv/flask-mailman
