### ISSUE TITLE
Winmail.dat on Office 365 AWS EB

### ISSUE THREAD

**Issue by shmuli9** [pallets-eco/flask-mail#170]
When using Flask-Mail on AWS to send emails via GoDaddy/Office 365 (Exchange), the emails arrive at destination packaged as a winmail.dat attachment. Despite extensive messing with Exchange settings this was unresolved. 

Upon switching to a different email plugin all works smoothly, so I believe this is an issue with Flask-Mail.

Wierdly, and very annoying for debugging, when testing on my local windows dev server, emails are sent fine without any winmail issues.

**Comment by davidism** [comment]
I have no way to reproduce or debug this issue. Check if it happens with Python's `smtplib` directly.
