### ISSUE TITLE
duplicate documentation site

### ISSUE THREAD

**Issue by zachvalenta** [pallets-eco/flask-mail#177]
There seem to be two `flask-mail` documentation sites on pythonhosted.org:

* current: https://pythonhosted.org/Flask-Mail/

![Screen Shot 2019-12-10 at 10 25 07 AM](https://user-images.githubusercontent.com/11388735/70542812-616e6f00-1b37-11ea-8f73-65f521c6dd94.png)

* outdated: https://pythonhosted.org/flask-mail/

![Screen Shot 2019-12-10 at 10 25 11 AM](https://user-images.githubusercontent.com/11388735/70542817-66332300-1b37-11ea-89e4-e73d38ca28ef.png)

Seems like there should only be one documentation site.

**Comment by zachvalenta** [comment]
Realized that the other docs site controlled by someone who may be outside the `flask-mail` project https://bitbucket.org/danjac/flask-mail/src/default/

In which case nothing can be done. Just checking in the event that something can.

**Comment by davidism** [comment]
The docs are now hosted at https://flask-mail.readthedocs.io. I've deleted the pythonhosted.org docs for Flask-Mail, but the lower case flask-mail ones remain up. I've reported that as a bug to Warehouse: https://github.com/pypi/warehouse/issues/16002
