### ISSUE TITLE
Unicode pt-BR

### ISSUE THREAD

**Issue by engmsilva** [pallets-eco/flask-mail#178]
Is there a simple way to configure flask-email to accept unicode pt-BR?

This is flask-mail configuration:

```
msg = Message(
        subject,
        sender=mail_settings.get("MAIL_USERNAME"),
        recipients=[email],
        body='Olá como vai você'.encode('utf-8'),
        charset='utf-8'
        ) 
```
I get the following error:

```
 msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 322: ordinal not in range(128)
```

Strangely the subject accepts unicode

**Comment by ThiefMaster** [comment]
Well you are passing utf-8 bytes and not unicode fro the body right now...

**Comment by engmsilva** [comment]
which parameter to configure to pass the unicode?

**Comment by davidism** [comment]
A body with unicode characters seems to be supported correctly, no `.encode` call needed.
