### ISSUE TITLE
Travis-ci: build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [pallets-eco/flask-mail#184]
Hi,

Some build is failing on AMD64 for python:2.6 and 3.3. 
Please see here full log: https://docs.travis-ci.com/user/languages/python/
I searched here https://docs.travis-ci.com/user/languages/python/ , these python is not having travis support.

And i dont see any travis build generation fo rthis project.

So is the travis disabled? Or some other issue.

Please let me know.

Thanks !!

**Comment by davidism** [comment]
Now using GitHub instead of Travis for CI.
