### ISSUE TITLE
A modern Alternative

### ISSUE THREAD

**Issue by waynerv** [pallets-eco/flask-mail#188]
Since flask-mail has not been maintained for many years, I created a new Flask mail extension - [flask-mailman](https://github.com/waynerv/flask-mailman), its core implementation is ported from Django's `mail` module, and which has the following advantages over `flask-mail`.
- Built-in multiple mail backends, as well as support for customization.
- The same simple and intuitive call interface.
- Regularly synchronized with Django‘s new features and bug fixes.

If you encounter problems with flask-mail, feel free to have a try.

**Comment by wlach** [comment]
A group of us have been working to reactivate this project, which has now moved to the pallets-eco organization. Closing this, not making any statements about the merits of continuing to use flask-mail vs. switching to an alternative (people should use what makes them happy)

**Comment by davidism** [comment]
Flask-Mail is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on [the Pallets Discord server](https://discord.gg/pallets).
