### ISSUE TITLE
Archive the repository and add a warning to the documentation page

### ISSUE THREAD

**Issue by marksteward** [pallets-eco/flask-mail#194]
This project's no longer maintained. As a final task, could you put the project to rest by documenting that people shouldn't start using it for new projects, and potentially point to another project?

Thanks for all the work on it so far.

**Comment by doekman** [comment]
see https://github.com/waynerv/flask-mailman

**Comment by davidism** [comment]
Flask-Mail is now part of the Pallets Community Ecosystem. Pallets is the open source organization that maintains Flask; Pallets-Eco enables community maintenance of Flask extensions. If you are interested in helping maintain this project, please reach out on [the Pallets Discord server](https://discord.gg/pallets).
