### ISSUE TITLE
Support other mail services (Google App Engine, Amazon SES, etc)

### ISSUE THREAD

**Issue by techniq** [pallets-eco/flask-mail#21]
We discussed this in a Flask-Security issue, but thought I'd put in an issue here to keep track.  It would be helpful if you could use the Flask-Mail API to to send mail via a mail service, such as Google App Engine (https://developers.google.com/appengine/docs/python/mail/sendingmail) or Amazon SES (http://aws.amazon.com/ses/).  I'm not overly familiar with SES, but it might require using 'boto' to access the API to send email.

**Comment by nfvs** [comment]
+1 :thumbsup:

**Comment by j-walker23** [comment]
+1

**Comment by herman5** [comment]
+1 for sendgrid support :)

**Comment by SimonHurst** [comment]
SES support would be nice or just away to set the "reply-to" address in config. Apologise in advance if this is already possible i just haven't worked it out yet. Currently using flask-security and I can't see an obvious way to set it without having to re-write some of the code.

**Comment by Tomazz** [comment]
+1

**Comment by Fohlen** [comment]
This would also be nice in order to have command line backend for sending (testing)

**Comment by davidism** [comment]
For now, this is outside the scope of this extension. Flask-Mail supports SMTP. Most services that offer mail sending APIs also provide SMTP interfaces. There are other mail extensions that provide custom backends, if that's really needed.
