### ISSUE TITLE
Consider adding an integration test for flask-mail that verifies things are sent on the SMTP level

### ISSUE THREAD

**Issue by wlach** [pallets-eco/flask-mail#210]
(from the pycon 2024 sprints)

At the moment it doesn't appear that this project has anything like this in its unit tests, might be desirable? I am thinking of something that tests that this basic thing works:

```py
from flask import Flask
from flask_mail import Mail
from flask_mail import Message


app = Flask(__name__)
mail = Mail(app)


@app.route("/")
def index():

    msg = Message("Hello", sender="from@example.com", recipients=["wrlach@gmail.com"])
    mail.send(msg)
```

**Comment by danwuSBU** [comment]
planning to look during PyCon 2024 sprints

**Comment by wlach** [comment]
> planning to look during PyCon 2024 sprints

Foundational work to make testing/repo level work in standard ways has merged, so I think this can be worked on without fear. I would personally add a new file called `tests/test_integration.py` and write a plain pytest to what's described in the issue. The core pallets maintainers may have more suggestions on the best way of implementing this.
