### ISSUE TITLE
MAIL_SUPPRESS_SEND description in docs

### ISSUE THREAD

**Issue by iurisilvio** [pallets-eco/flask-mail#34]
From docs/index.rst:

> If the setting TESTING is set to True, emails will be suppressed. Calling send() on your messages will not result in any messages being actually sent.
> 
> Alternatively outside a testing environment you can set MAIL_SUPPRESS_SEND to False. This will have the same effect.

The text is confuse or wrong. "This will have the same effect" of what? If I set `MAIL_SUPPRESS_SEND=False`, messages will be sent. The paragraph before this one says about "messages not sent".

**Comment by bepetersn** [comment]
Yeah, the docs seem to imply that setting MAIL_SUPPRESS_SEND=False will suppress emails, which is the exact opposite of what it should be, semantically.
