### ISSUE TITLE
Connection Pooling

### ISSUE THREAD

**Issue by peteroconnor** [pallets-eco/flask-mail#38]
In addition to one connection per email and the bulk mode, when dealing with a high volume of user-driven email-sending tasks, it will be nice for Flask-Mail to maintain a connection pool.
- Ability to open/close connections based on the load
- Option to keep at least one connection for standby

**Comment by FindBoat** [comment]
I'm having the similar issue that my application is having some volume of random emails but the connection seems quite slow. Any workaround for now?

**Comment by davidism** [comment]
I think this is outside the scope of this extension.
