### ISSUE TITLE
Changelog should list all breaking changes

### ISSUE THREAD

**Issue by iurisilvio** [pallets-eco/flask-mail#51]
I discovered today after a version upgrade and some debugging, flask-mail changed `DEFAULT_MAIL_SENDER` to `MAIL_DEFAULT_SENDER`. It should be explicit in changelog.

In changelog you have `Changed configuration options to be less confusing` (https://github.com/mattupstate/flask-mail/commit/6e55aad47a3db69e70aec51225f8ebabfc0be2b5#diff-e4eb329834da3d36278b1b7d943b3bc9R12). This message does not help people upgrading the package.

To be clear, I'm not against this breaking change, just think it should be better documented.

**Comment by JocelynDelalande** [comment]
+1

Actually, IMHO, notifying it in the ChangeLog is the bare minimum, allowing the use of the old vars for some time with a DeprecationWarning would be better.
