### ISSUE TITLE
Minor doc bug

### ISSUE THREAD

**Issue by rsalmond** [pallets-eco/flask-mail#54]
Docs [here](http://pythonhosted.org/Flask-Mail/) indicate default sender config var is MAIL_DEFAULT_SENDER.

However docs [here](http://pythonhosted.org/flask-mail/) are doing a Yoda thing. Had to grep source (and learn a bit about flask extension configs :smile:) to figure it out.

**Comment by davidism** [comment]
Docs are now hosted at https://flask-mail.readthedocs.io.
