### ISSUE TITLE
RuntimeError: working outside of application context

### ISSUE THREAD

**Issue by dtheodor** [pallets-eco/flask-mail#63]
When using the mailer to send an e-mail from a background worker (that is, outside of the Flask application context), it crashes and burns.

**Comment by dtheodor** [comment]
Due to the requirement "one `Mail` instance and multiple `Flask` apps all configured through the `Mail` instance's `init_app`", I don't think what I had in mind is possible. The `Mail` object then always needs the `current_app` to figure out which app (aka mail configuration) it should use. If it is instantiated through `Mail(app)`, it already works without requiring the `current_app` to be set. You can close the issue as `cannot fix` as far as I am concerned.

**Comment by TechStuffBoy** [comment]
After six years, But yeah i hope this might hint for other developers.

Thread(
      target=copy_current_app_context(send_async_email),
      args=(current_app._get_current_object(), msg),
    ).start()

We need to use get_current_object().

https://github.com/pgjones/quart/issues/56

**Comment by davidism** [comment]
You must be inside a context to access `current_app`. Either you're in a request or a CLI command, in which case this is already true, or you push one manually `with app.app_context():`. This is a general pattern in Flask and extensions.
