### ISSUE TITLE
DEFAULT_MAIL_SENDER not seen

### ISSUE THREAD

**Issue by sliptonic** [pallets-eco/flask-mail#72]
I have the default mail sender set as a config variable. I use the python debuggingserver on my development box,  and Sendmail on the server.

I'm sending email from a celery task. If I call the procedures directly without using celery, everything works fine. If I use celery, it errors out because it doesn't see DEFAULT_MAIL_SENDER.
I work around it by including this line: msg.sender = mail.app.config['DEFAULT_MAIL_SENDER']
Strangely, when I run it on the server, it works fine, even when called from a celery task.

**Comment by JocelynDelalande** [comment]
I don't know if the doc issue is solved, but it seems that bug can be closed.

**Comment by calebhfaber** [comment]
Looks like the doc issue is still there. It took me a while to find this thread and was so confused because I was following the old documentation and couldn't find anything else.
