### ISSUE TITLE
Subject encoding error with Python3.4

### ISSUE THREAD

**Issue by harobed** [pallets-eco/flask-mail#88]
This line https://github.com/mattupstate/flask-mail/blob/master/flask_mail.py#L385 don't work with Python3.4

With :

```
           return self._message().as_string().encode(self.charset or 'utf-8')
```

Subject encoding work with success.

With :

```
            return self._message().as_bytes()
```

Subject encoding fail.

I suggest to always use : 

```
           return self._message().as_string().encode(self.charset or 'utf-8')
```

**Comment by harobed** [comment]
bump

**Comment by davidism** [comment]
If `email.Message.as_bytes()` is failing on something it shouldn't, that seems to be an issue to report to Python's smtplib. 3.8 is the lowest supported version in 2024, and it does not appear to have an issue.
