### ISSUE TITLE
Attachment filenames with unicode characters

### ISSUE THREAD

**Issue by phalgun** [pallets-eco/flask-mail#97]
How do I send an attachment with unicode characters in its filename.

I notice the option `MAIL_ASCII_ATTACHMENTS` when set to True, strips the file names off their unicode characters. 

But I want to able to send unicode characters in the filenames. Is there a way to do it?

**Comment by davidism** [comment]
I can't reproduce this issue. Attachments with Unicode characters in filenames send successfully.
