### ISSUE TITLE
pypy3 error

### ISSUE THREAD

**Issue by brizjin** [pallets-eco/flask-mail#99]
Hello! I using Flask on pypy3 and all packages working well, except flask_mail. I have this error:

File "/usr/local/site-packages/flask_mail.py", line 41, in <module>
    from email import policy
ImportError: cannot import name 'policy'

**Comment by davidism** [comment]
PyPy3 targets Python 3.2 currently, and `email.policy` was added in 3.3.

**Comment by wlach** [comment]
We only support python 3.8+ in the latest version (unreleased)
